service: refine-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
