service: refine-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2
  environment:
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET}

plugins:
  - serverless-offline

functions:
  unauthenticated:
    handler: handler-unauthenticated.handler
    events:
      - httpApi:
          path: /api/google-authenticate
          method: post
      - httpApi:
          path: /api/google-refresh
          method: post
