service: refine-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2
  environment:
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET}
    GOOGLE_SERVICE_ACCOUNT_KEY: ${env:GOOGLE_SERVICE_ACCOUNT_KEY}
    REFINE_LMS_DATABASE: ${env:REFINE_LMS_DATABASE, 'refine-dev'}
    MONGO_CONNECTION_STRING: ${env:MONGO_CONNECTION_STRING, 'mongodb://localhost:27017'}
  httpApi:
    authorizers:
      google:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: 'https://accounts.google.com'
        audience: '440807713733-li6c8t0f1pmjrlaceen6afndskghlrrm.apps.googleusercontent.com'

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: true
    target: node20

package:
  individually: true
  exclude:
    - .git/**
    - .gitignore
    - .DS_Store
    - npm-debug.log
    - .serverless/**
    - .serverless_plugins/**
    - '*.ts'
    - '*.spec.js'
    - '*.json'
    - '**/LICENSE'
    - '**/license'
    - '**/*.md'
    - '**/*.ts'
    - '*.md'
    - '*.xml'
    - 'jest.config.js'
    - coverage/**
    - reports/**

build:
  esbuild: false

functions:
  unauthenticated:
    handler: handler-unauthenticated.handler
    timeout: 10
    events:
      - httpApi:
          path: /api/google-authenticate
          method: post
      - httpApi:
          path: /api/google-refresh
          method: post
  authenticated:
    handler: handler-authenticated.handler
    timeout: 10
    events:
      - httpApi:
          path: /api/visible-schools
          method: get
          authorizer:
            name: google
      - httpApi:
          path: /api/create-school
          method: post
          authorizer:
            name: google
      - httpApi:
          path: /api/relevant-school-info
          method: get
          authorizer:
            name: google
      - httpApi:
          path: /api/create-year-group
          method: post
          authorizer:
            name: google
      - httpApi:
          path: /api/create-course
          method: post
          authorizer:
            name: google
      - httpApi:
          path: /api/create-class
          method: post
          authorizer:
            name: google
      - httpApi:
          path: /api/invite
          method: post
          authorizer:
            name: google
      - httpApi:
          path: /api/join-school
          method: post
          authorizer:
            name: google
      - httpApi:
          path: /api/decline-invitation
          method: post
          authorizer:
            name: google
      - httpApi:
          path: /api/remove-user
          method: post
          authorizer:
            name: google
      - httpApi:
          path: /api/add-to-class
          method: post
          authorizer:
            name: google
      - httpApi:
          path: /api/remove-from-class
          method: post
          authorizer:
            name: google
      - httpApi:
          path: /api/school-structure
          method: get
          authorizer:
            name: google
      - httpApi:
          path: /api/request-to-join-class
          method: post
          authorizer:
            name: google
      - httpApi:
          path: /api/add-syllabus-content
          method: post
          authorizer:
            name: google
      - httpApi:
          path: /api/remove-syllabus-content
          method: post
          authorizer:
            name: google
      - httpApi:
          path: /api/create-post
          method: post
          authorizer:
            name: google
      - httpApi:
          path: /api/list-posts
          method: post
          authorizer:
            name: google
      - httpApi:
          path: /api/attachment-link
          method: post
          authorizer:
            name: google
      - httpApi:
          path: /api/post
          method: post
          authorizer:
            name: google
      - httpApi:
          path: /api/add-attachment-to-submission
          method: post
          authorizer:
            name: google
      - httpApi:
          path: /api/submit-assignment
          method: post
          authorizer:
            name: google
      - httpApi:
          path: /api/record-marks
          method: post
          authorizer:
            name: google
