service: refine-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2
  environment:
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET}
    REFINE_LMS_DATABASE: ${env:REFINE_LMS_DATABASE, 'refine-dev'}
    MONGO_CONNECTION_STRING: ${env:MONGO_CONNECTION_STRING, 'mongodb://localhost:27017'}
  httpApi:
    authorizers:
      google:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: 'https://accounts.google.com'
        audience: '440807713733-li6c8t0f1pmjrlaceen6afndskghlrrm.apps.googleusercontent.com'

plugins:
  - serverless-offline

functions:
  unauthenticated:
    handler: handler-unauthenticated.handler
    events:
      - httpApi:
          path: /api/google-authenticate
          method: post
      - httpApi:
          path: /api/google-refresh
          method: post
  authenticated:
    handler: handler-authenticated.handler
    events:
      - httpApi:
          path: /api/visible-schools
          method: get
          authorizer:
            name: google
