service: refine-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2

plugins:
  - serverless-offline

functions:
  unauthenticated:
    handler: handler-unauthenticated.handler
    events:
      - httpApi:
          path: /google-authenticate
          method: post
