name: ui-prod

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/ui-prod.yml'
      - 'ui/**'
      - 'data/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'ui/package-lock.json'

      - name: Node Install Dependencies
        run: npm ci

#      - name: Build Dev UI to Deploy
#        run: npm run build:dev
#
#      - name: Sync the UI to the S3 buckets
#        run: aws s3 sync ./build/ s3://refine-lms-ui-dev/
#
#      - name: Invalidate CloudFront
#        run: aws cloudfront create-invalidation --distribution-id x --paths "/*"

      - name: Build Prod UI to Deploy
        run: npm run build

      - name: Sync the UI to the S3 buckets
        run: aws s3 sync ./dist/ s3://refine-lms-ui-prod/

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id E1UHI2SRVWY7GF --paths "/*"
